"""
Open a GitHub pull request with the agent's changes.

Takes the diff produced by the agent, commits it to a new branch,
and opens a PR against the original issue's repo.

The PR description is auto-generated and:
  - Links back to the original issue
  - Explains what was changed and why (from the agent's <DONE> conclusion)
  - Lists the files changed
  - Notes that it was generated by the Autonomous-SWE-Agent
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass

from github import Github, GithubException
from tenacity import retry, stop_after_attempt, wait_exponential

from codepilot.integrations.github.issue_fetcher import IssueData


@dataclass
class PRResult:
    """Result of creating a pull request."""

    pr_url: str
    pr_number: int
    branch_name: str
    files_changed: list[str]


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10),
    reraise=True,
)
def create_pr(
    issue_data: IssueData,
    diff: str,
    conclusion: str,
    token: str | None = None,
    repo_local_path: str | None = None,
) -> PRResult:
    """
    Commit the agent's changes and open a GitHub pull request.

    Args:
        issue_data:       The fetched issue data (repo, issue number, etc.)
        diff:             The unified diff of all changes made.
        conclusion:       The agent's explanation of what it changed.
        token:            GitHub personal access token.
        repo_local_path:  Path to the cloned repo on disk (for git operations).
                          If None, creates a temp clone.

    Returns:
        PRResult with the PR URL and metadata.
    """
    token = token or os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN required to create pull requests")

    gh = Github(token)
    repo = gh.get_repo(issue_data.repo_full_name)

    branch_name = f"codepilot/fix-issue-{issue_data.issue_number}"

    # If we have the local repo path, use git to commit and push
    if repo_local_path:
        files_changed = _commit_and_push(
            repo_local_path, branch_name, issue_data, conclusion, token
        )
    else:
        files_changed = _parse_changed_files(diff)

    # Build PR body
    pr_body = _build_pr_body(issue_data, diff, conclusion, files_changed, branch_name)

    try:
        pr = repo.create_pull(
            title=f"Fix: {issue_data.issue_title}",
            body=pr_body,
            head=branch_name,
            base=issue_data.branch,
        )

        # Link PR to the issue
        try:
            issue = repo.get_issue(issue_data.issue_number)
            issue.create_comment(
                f"CodePilot has opened a pull request to fix this issue: {pr.html_url}"
            )
        except GithubException:
            pass  # Comment failure is non-fatal

        return PRResult(
            pr_url=pr.html_url,
            pr_number=pr.number,
            branch_name=branch_name,
            files_changed=files_changed,
        )

    except GithubException as exc:
        if "already exists" in str(exc):
            # PR already open for this branch — return existing PR
            pulls = list(repo.get_pulls(head=branch_name))
            if pulls:
                return PRResult(
                    pr_url=pulls[0].html_url,
                    pr_number=pulls[0].number,
                    branch_name=branch_name,
                    files_changed=files_changed,
                )
        raise


def _commit_and_push(
    repo_path: str,
    branch_name: str,
    issue_data: IssueData,
    conclusion: str,
    token: str,
) -> list[str]:
    """Create a git branch, commit changes, and push to GitHub.

    Every git call is an argument list, never a shell string: the commit
    message carries the issue title, which anyone who can open an issue
    controls. The original interpolated it into `git commit -m "..."` under
    `shell=True`, which ran `" & cmd & "` on Windows and `$(cmd)` on POSIX.
    """

    def git(*args: str) -> subprocess.CompletedProcess:
        result = subprocess.run(
            ["git", "-c", "user.email=codepilot@localhost", "-c", "user.name=CodePilot", *args],
            cwd=repo_path, capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"git {args[0]} failed: {result.stderr.strip()[:300]}")
        return result

    git("checkout", "-b", branch_name)
    git("add", "-A")
    status = git("diff", "--cached", "--name-only")
    files_changed = [f.strip() for f in status.stdout.splitlines() if f.strip()]
    commit_msg = (
        f"Fix issue #{issue_data.issue_number}: {issue_data.issue_title}\n\n"
        f"{conclusion}\n\n"
        f"Fixes #{issue_data.issue_number}"
    )
    git("commit", "-q", "-m", commit_msg)
    _push(repo_path, issue_data.repo_url, branch_name, token)
    return files_changed


def _push(repo_path: str, repo_url: str, branch_name: str, token: str) -> None:
    """Push with the token in an HTTP header passed through the environment.

    The original pushed to `https://{token}@github.com/...`, which puts the
    token on the command line (readable in the process list) and in git's
    error output. GIT_CONFIG_COUNT/KEY/VALUE (git >= 2.31) keeps it in the
    child's environment only.
    """
    import base64
    import os

    basic = base64.b64encode(f"x-access-token:{token}".encode()).decode()
    env = {
        **os.environ,
        "GIT_CONFIG_COUNT": "1",
        "GIT_CONFIG_KEY_0": "http.https://github.com/.extraheader",
        "GIT_CONFIG_VALUE_0": f"AUTHORIZATION: basic {basic}",
        "GIT_TERMINAL_PROMPT": "0",
    }
    result = subprocess.run(
        ["git", "push", repo_url, f"{branch_name}:{branch_name}"],
        cwd=repo_path, capture_output=True, text=True, env=env,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git push failed: {result.stderr.replace(token, '***').strip()[:300]}")


def _parse_changed_files(diff: str) -> list[str]:
    """Extract changed file paths from a unified diff."""
    import re

    files = re.findall(r"^--- a/(.+)$", diff, re.MULTILINE)
    return files or []


def _build_pr_body(
    issue_data: IssueData,
    diff: str,
    conclusion: str,
    files_changed: list[str],
    branch_name: str = "",
) -> str:
    """Build the PR description."""
    branch_name = branch_name or f"codepilot/fix-issue-{issue_data.issue_number}"
    files_list = "\n".join(f"- `{f}`" for f in files_changed) or "- (see diff)"
    diff_lines = len(diff.splitlines())

    return f"""## Summary

Fixes #{issue_data.issue_number}

{conclusion}

## Changes

{files_list}

**Diff size:** {diff_lines} lines

## How to test

```bash
git fetch origin {branch_name}
git checkout {branch_name}
python -m pytest
```

---
*Opened by CodePilot, a coding agent. The change was written by a model and has
not been reviewed by a person; review it as you would any outside contribution.*
"""
