"""
Open a GitHub pull request with the agent's changes.

Takes the diff produced by the agent, commits it to a new branch,
and opens a PR against the original issue's repo.

The PR description is auto-generated and:
  - Links back to the original issue
  - Explains what was changed and why (from the agent's <DONE> conclusion)
  - Lists the files changed
  - Notes that it was generated by the Autonomous-SWE-Agent
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass

from github import Github, GithubException
from tenacity import retry, stop_after_attempt, wait_exponential

from github_integration.issue_fetcher import IssueData


@dataclass
class PRResult:
    """Result of creating a pull request."""

    pr_url: str
    pr_number: int
    branch_name: str
    files_changed: list[str]


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10),
    reraise=True,
)
def create_pr(
    issue_data: IssueData,
    diff: str,
    conclusion: str,
    token: str | None = None,
    repo_local_path: str | None = None,
) -> PRResult:
    """
    Commit the agent's changes and open a GitHub pull request.

    Args:
        issue_data:       The fetched issue data (repo, issue number, etc.)
        diff:             The unified diff of all changes made.
        conclusion:       The agent's explanation of what it changed.
        token:            GitHub personal access token.
        repo_local_path:  Path to the cloned repo on disk (for git operations).
                          If None, creates a temp clone.

    Returns:
        PRResult with the PR URL and metadata.
    """
    token = token or os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN required to create pull requests")

    gh = Github(token)
    repo = gh.get_repo(issue_data.repo_full_name)

    branch_name = f"swe-agent/fix-issue-{issue_data.issue_number}"

    # If we have the local repo path, use git to commit and push
    if repo_local_path:
        files_changed = _commit_and_push(
            repo_local_path, branch_name, issue_data, conclusion, token
        )
    else:
        files_changed = _parse_changed_files(diff)

    # Build PR body
    pr_body = _build_pr_body(issue_data, diff, conclusion, files_changed)

    try:
        pr = repo.create_pull(
            title=f"Fix: {issue_data.issue_title}",
            body=pr_body,
            head=branch_name,
            base=issue_data.branch,
        )

        # Link PR to the issue
        try:
            issue = repo.get_issue(issue_data.issue_number)
            issue.create_comment(
                f"Autonomous-SWE-Agent has opened a pull request to fix this issue: {pr.html_url}"
            )
        except GithubException:
            pass  # Comment failure is non-fatal

        return PRResult(
            pr_url=pr.html_url,
            pr_number=pr.number,
            branch_name=branch_name,
            files_changed=files_changed,
        )

    except GithubException as exc:
        if "already exists" in str(exc):
            # PR already open for this branch — return existing PR
            pulls = list(repo.get_pulls(head=branch_name))
            if pulls:
                return PRResult(
                    pr_url=pulls[0].html_url,
                    pr_number=pulls[0].number,
                    branch_name=branch_name,
                    files_changed=files_changed,
                )
        raise


def _commit_and_push(
    repo_path: str,
    branch_name: str,
    issue_data: IssueData,
    conclusion: str,
    token: str,
) -> list[str]:
    """Create a git branch, commit changes, and push to GitHub."""

    def git(cmd: str, **kwargs) -> subprocess.CompletedProcess:
        return subprocess.run(
            cmd, shell=True, cwd=repo_path, capture_output=True, text=True, **kwargs
        )

    # Configure git
    git('git config user.email "swe-agent@autonomous"')
    git('git config user.name "Autonomous-SWE-Agent"')

    # Create branch
    git(f"git checkout -b {branch_name}")

    # Stage all changes
    git("git add -A")

    # Get changed files
    status = git("git diff --cached --name-only")
    files_changed = [f.strip() for f in status.stdout.splitlines() if f.strip()]

    # Commit
    commit_msg = (
        f"Fix issue #{issue_data.issue_number}: {issue_data.issue_title}\n\n"
        f"{conclusion}\n\n"
        f"Fixes #{issue_data.issue_number}"
    )
    git(f'git commit -m "{commit_msg}"')

    # Push with token auth
    remote_url = issue_data.repo_url.replace("https://", f"https://{token}@")
    git(f"git push {remote_url} {branch_name}")

    return files_changed


def _parse_changed_files(diff: str) -> list[str]:
    """Extract changed file paths from a unified diff."""
    import re

    files = re.findall(r"^--- a/(.+)$", diff, re.MULTILINE)
    return files or []


def _build_pr_body(
    issue_data: IssueData,
    diff: str,
    conclusion: str,
    files_changed: list[str],
) -> str:
    """Build the PR description."""
    files_list = "\n".join(f"- `{f}`" for f in files_changed) or "- (see diff)"
    diff_lines = len(diff.splitlines())

    return f"""## Summary

Fixes #{issue_data.issue_number}

{conclusion}

## Changes

{files_list}

**Diff size:** {diff_lines} lines

## How to test

```bash
# Clone and checkout this branch
git checkout {issue_data.issue_number}

# Run the relevant tests
pytest tests/ -x -q
```

---
*This pull request was generated by [Autonomous-SWE-Agent](https://github.com/shiva-shivanibokka/Autonomous-SWE-Agent), \
a production SWE agent benchmarked on SWE-bench-lite.*
"""
